#!/bin/sh

## AUTOSTART ##
killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
sxhkd &

$HOME/.config/bspwm/polybar-bspwm.sh

xrandr -s 1920x1080
setxkbmap us altgr-intl
xwallpaper --zoom ~/Pictures/cyborg_gruv.png

## Monitor
for monitor in $(bspc query -M); do
  bspc monitor $monitor -d 1 2 3 4 5 6
done

## BSPWM Config idk
bspc config border_width    2 
bspc config window_gap      12

bspc config click_to_focus true
bspc config focus_follows_pointer false

bspc config single_monocle      true
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config paddingless_monocle true

## Colors
bspc config normal_border_color   "#4c566a"
bspc config active_border_color   "#1e1e1e"
bspc config focused_border_color  "#5e81ac"
bspc config presel_feedback_color "#5e81ac"
bspc config urgen_border_color    "#dd2727"

## Rules
bspc rule -a Emacs state=tiled
