require("core.plugin_config.harpoon")
require("core.plugin_config.lsp_config")
require("core.plugin_config.telescope")
require("core.plugin_config.themes")
require("core.plugin_config.toolset")
require("core.plugin_config.treesitter")
require("core.plugin_config.ui")
