#!/bin/sh

# colors
# bg / fg
bgcol=#201e23


# reds
red=#bf616a
red1=#d92d26
red2=#A60300

# pinks

# purples
purple=#7681c5

# blues
blue=#00d3eb
blue1=#72e6cb

# greens
green=#94af7d
green1=#9fcb8d

# yellows
yellow=#d2c661

# oranges
orange=#f27c00
orange1=#efa514

# Whites/Blacks/Grays
gray=#81a1c1
black=#191919

# Bar icons
kernelcol=#72e6cb
pacmancol=#94af7d
wificol=#7681c5
diskcol=#81a1c1
memcol=#bf616a
datecol=#d2c661
volcol=#9fcb8d
brightcol=#efa514
