require("core.plugin_config.completions")
require("core.plugin_config.lsp_config")
require("core.plugin_config.neovide")
require("core.plugin_config.toolset")
require("core.plugin_config.themes")
require("core.plugin_config.treesitter")
require("core.plugin_config.ui")
